#!/bin/sh
#

# For RHEL Linux systems
# receiver          Start/Stop sync
#
# chkconfig: 35 98 10
# description: receiver service
# processname: receiver
# config:
# pidfile: /var/run/receiver.pid

# For Ubuntu Linux systems
### BEGIN INIT INFO
# Provides:          receiver
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Should-Start:      $named
# Should-Stop:       $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start ZMQ receiver
# Description:       Start the receiver service to receive images via ZMQ
### END INIT INFO


# Use Java 7
PATH=/opt/jre/bin:$PATH
export PATH

USER=det
HOME=/opt/receiver
SU="su --login  $USER --command  "

LOGFILE=/var/log/receiver

touch $LOGFILE
chown $USER $LOGFILE

case "$1" in
start)
  $SU "PATH=/opt/jre/bin:$PATH $HOME/latest/bin/receiver -d /ramdisk -p 8080 > $LOGFILE 2>&1 &"
  ;;
stop)
  $SU "pkill -f 'java .* $HOME' >> $LOGFILE 2>&1 &"
  ;;
\*)
  echo "usage: $0 (start|stop|help)"
esac